name: Deploy to webvm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy outer site on webvm
        run: |
          cd /opt/sites/personal-portfolio
          git pull

          cd /opt/sites
          docker compose build outer
          docker compose up -d outer
